env: "local"
http_server:
  address: "0.0.0.0:8000"
  timeout: 4s
  idle_timeout: 30s
db:
  name: "cloud_render_api"
  user: "user"
  password: "password"
  host: "postgres"
  port: "5432"
redis:
  address: "redis:6379"
  password: "password"
  queue_name: "render-list"
  priority_queue_name: "subscribed-render-list"
payments:
  sub_premium_month: "sub-premium-month"
subscriptions:
  premium: "premium"
