env: "local"
http_server:
  address: "0.0.0.0:8002"
  timeout: 4s
  idle_timeout: 30s
redis:
  address: "localhost:6379"
  queue_name: "render-list"
  priority_queue_name: "subscribed-render-list"
  max_priority_in_a_row: 5